# Generated by Django 5.0.6 on 2024-06-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='preparetion_steps',
            new_name='ficha_tecnica',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='preparation_time',
            new_name='speed',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='preparation_time_unit',
            new_name='speed_quant',
        ),
    ]
